Repository shyamd/mkdocs-bibtex, pull requests merged in 2025-01, with the labels that each got.

#288 Zotero pagination
  .github/workflows/testing.yml
  requirements-testing.txt
  src/mkdocs_bibtex/utils.py
  test_files/test_plugin.py
  test_files/test_utils.py
Labels: release:minor

#285 Refactor for easier updating
  .github/workflows/testing.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  example/docs/full_bib.md
  example/docs/index.md
  example/mkdocs.yml
  example/nature.csl
  example/refs.bib
  example/springer-basic-author-date.csl
  pyproject.toml
  requirements-testing.txt
  requirements.txt
  setup.py
  src/mkdocs_bibtex/citation.py
  src/mkdocs_bibtex/config.py
  src/mkdocs_bibtex/plugin.py
  src/mkdocs_bibtex/registry.py
  src/mkdocs_bibtex/utils.py
  test_files/test_citation.py
  test_files/test_features.py
  test_files/test_integration.py
  test_files/test_pandoc_registry.py
  test_files/test_plugin.py
  test_files/test_simple_registry.py
  test_files/test_utils.py
Labels: release:major

#290 FIX: Not invalidating citation blocks with 0 citations
  src/mkdocs_bibtex/citation.py
  test_files/test_citation.py
  test_files/test_integration.py
Labels: release:patch

#291 Inline References
  src/mkdocs_bibtex/citation.py
  src/mkdocs_bibtex/plugin.py
  src/mkdocs_bibtex/registry.py
  test_files/test_citation.py
  test_files/test_integration.py
  test_files/test_pandoc_registry.py
  test_files/test_simple_registry.py
Labels: release:minor
